name: style-dictionary-build
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: init
      - uses: amzn/style-dictionary@3.7.1
      - name: build
        run: style-dictionary build