name: style-dictionary-build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: cd .. && ls -al
      - name: Link dependencies
        run: yarn
      - name: build
        run: yarn build